name: 'Release NPM Packages'
description: 'Downloads binaries, organizes them for CLI packages, and publishes to NPM'

inputs:
  npm-token:
    description: 'NPM authentication token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download all binaries
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Organize binaries for CLI
      shell: bash
      run: |
        echo "📦 Organizing binaries for CLI packages..."

        declare -A PLATFORM_MAP=(
          ["x86_64-unknown-linux-gnu"]="cli-linux-x64"
          ["aarch64-unknown-linux-gnu"]="cli-linux-arm64"
          ["x86_64-apple-darwin"]="cli-darwin-x64"
          ["aarch64-apple-darwin"]="cli-darwin-arm64"
          ["x86_64-pc-windows-msvc"]="cli-win32-x64"
        )

        found_count=0
        missing_count=0

        for rust_target in "${!PLATFORM_MAP[@]}"; do
          npm_platform="${PLATFORM_MAP[$rust_target]}"
          dest_dir="packages/cli/npm/$npm_platform"

          if [[ "$rust_target" == *"windows"* ]]; then
            binary_pattern="tscanner-${rust_target}.exe"
            dest_name="tscanner.exe"
          else
            binary_pattern="tscanner-${rust_target}"
            dest_name="tscanner"
          fi

          binary_file=$(find artifacts -type f -name "$binary_pattern" 2>/dev/null | head -1)

          if [ -n "$binary_file" ]; then
            mkdir -p "$dest_dir"
            cp "$binary_file" "$dest_dir/$dest_name"
            chmod +x "$dest_dir/$dest_name" 2>/dev/null || true
            echo "✅ Copied $npm_platform binary"
            found_count=$((found_count + 1))
          else
            missing_count=$((missing_count + 1))
          fi
        done

        echo ""
        echo "📦 Summary: $found_count binaries copied, $missing_count not found"

        if [ $found_count -gt 0 ]; then
          echo "📦 CLI binaries ready:"
          find packages/cli/npm -type f \( -name "tscanner" -o -name "tscanner.exe" \) -exec ls -lh {} \;
        fi

    - name: Generate scoped npm packages
      shell: bash
      run: |
        echo "📦 Generating scoped @tscanner packages..."
        pnpm --filter tscanner run script:fix-packages
        echo "✅ Scoped packages generated"

    - name: Publish NPM packages
      shell: bash
      run: bash scripts/publish-npm-package.sh
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
