name: 'Build Rust Binary'
description: 'Builds tscanner-server binary for a specific target platform'

inputs:
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu)'
    required: true
  os:
    description: 'Operating system (ubuntu-latest, macos-latest, windows-latest)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: packages/rust-core
        shared-key: ${{ inputs.target }}

    - name: Install cross-compilation tools (Linux ARM64)
      if: inputs.target == 'aarch64-unknown-linux-gnu'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Configure linker for ARM64
      if: inputs.target == 'aarch64-unknown-linux-gnu'
      shell: bash
      run: |
        mkdir -p .cargo
        cat > .cargo/config.toml << EOF
        [target.aarch64-unknown-linux-gnu]
        linker = "aarch64-linux-gnu-gcc"
        EOF

    - name: Build binary
      shell: bash
      working-directory: packages/rust-core
      run: cargo build --release --target ${{ inputs.target }}

    - name: Prepare binaries
      shell: bash
      run: |
        cd packages/rust-core/target/${{ inputs.target }}/release
        if [[ "${{ inputs.os }}" == "windows-latest" ]]; then
          cp tscanner-server.exe tscanner-server-${{ inputs.target }}.exe
          cp tscanner.exe tscanner-${{ inputs.target }}.exe
        else
          cp tscanner-server tscanner-server-${{ inputs.target }}
          cp tscanner tscanner-${{ inputs.target }}
        fi

    - name: Upload server binary (Unix)
      if: inputs.os != 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: binary-server-${{ inputs.target }}
        path: packages/rust-core/target/${{ inputs.target }}/release/tscanner-server-${{ inputs.target }}

    - name: Upload server binary (Windows)
      if: inputs.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: binary-server-${{ inputs.target }}
        path: packages/rust-core/target/${{ inputs.target }}/release/tscanner-server-${{ inputs.target }}.exe

    - name: Upload CLI binary (Unix)
      if: inputs.os != 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: binary-cli-${{ inputs.target }}
        path: packages/rust-core/target/${{ inputs.target }}/release/tscanner-${{ inputs.target }}

    - name: Upload CLI binary (Windows)
      if: inputs.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: binary-cli-${{ inputs.target }}
        path: packages/rust-core/target/${{ inputs.target }}/release/tscanner-${{ inputs.target }}.exe
