name: Setup Node, Rust and install dependencies

description: Setup Node.js, Rust toolchain, install pnpm packages, and use caches

inputs:
  install-rust:
    description: 'Whether to install Rust toolchain'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      if: inputs.install-rust == 'true'
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Rust cache
      if: inputs.install-rust == 'true'
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: packages/core
        shared-key: rust-cache

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.22.0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml

    - name: Verify PNPM Cache Directory
      shell: sh
      run: |
        pnpm config set store-dir "$PNPM_CACHE_FOLDER"
        PNPM_STORE_PATH="$( pnpm store path --silent )"
        if [ ! -d "$PNPM_STORE_PATH" ]; then
          echo "PNPM store directory does not exist, creating it."
          mkdir -p "$PNPM_STORE_PATH"
        else
          echo "PNPM store directory exists."
        fi

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/*/node_modules
          shared/*/node_modules
        key: node_modules-${{ hashFiles('pnpm-lock.yaml') }}
      id: pnpm-cache

    - name: Install dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      shell: sh
      run: pnpm install --frozen-lockfile
