name: 'Release VSCode Extension'
description: 'Builds and publishes VSCode extension to VS Code Marketplace and Open VSX'

inputs:
  azure-pat:
    description: 'Azure DevOps Personal Access Token for VS Code Marketplace'
    required: true
  open-vsx-pat:
    description: 'Personal Access Token for Open VSX Registry'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build shared dependencies
      shell: bash
      run: pnpm turbo run build --filter=tscanner-common

    - name: Build extension
      shell: bash
      working-directory: packages/vscode-extension
      run: pnpm run build

    - name: Get version
      id: version
      shell: bash
      run: |
        VERSION=$(node -p "require('./packages/vscode-extension/package.json').version")
        echo "current=$VERSION" >> $GITHUB_OUTPUT
        echo "📦 Publishing version: $VERSION"

    - name: Publish to Open VSX Registry
      id: publishToOpenVSX
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ inputs.open-vsx-pat }}
        packagePath: ./packages/vscode-extension
        dependencies: false
        skipDuplicate: true

    - name: Publish to VS Code Marketplace
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ inputs.azure-pat }}
        registryUrl: https://marketplace.visualstudio.com
        extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
        dependencies: false
        skipDuplicate: true

    - name: Create release tag
      shell: bash
      run: bash scripts/release/create-release-tag.sh "vscode-extension" "${{ steps.version.outputs.current }}"

    - name: Summary
      shell: bash
      run: |
        echo "✅ VSCode extension v${{ steps.version.outputs.current }} published!"
        echo "📦 Extension no longer bundles binaries - users install via npm"
