name: 'Callable CI'

on:
  workflow_call:
    inputs:
      run_lint:
        description: 'Run lint checks'
        type: boolean
        required: true
      run_build:
        description: 'Run build'
        type: boolean
        required: true
      run_test:
        description: 'Run tests'
        type: boolean
        required: true
    secrets:
      TURBO_TOKEN:
        description: Turbo token for cache
        required: true
      TURBO_TEAM:
        description: Turbo team for cache
        required: true

env:
  CARGO_TERM_COLOR: always
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  lint:
    if: inputs.run_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-and-install
        with:
          install-rust: 'true'

      - name: Run lint
        run: pnpm run lint

      - name: Run format
        run: pnpm run format

      - name: Check if any changes were made
        run: git diff --exit-code

  build:
    if: inputs.run_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-and-install
        with:
          install-rust: 'true'

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Build all packages
        run: pnpm run build

  test:
    if: inputs.run_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-and-install
        with:
          install-rust: 'true'

      - name: Run tests
        run: pnpm run test
